[functions]
  external_node_modules = ["express", "ejs"]
  node_bundler = "esbuild"
  included_files = ["views/**", "public/**"]

[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/api/:splat"


[[redirects]]
  from = "/images/*"
  to = "/public/images/:splat"
  status = 200

[[redirects]]
  from = "/stylesheets/*"
  to = "/public/stylesheets/:splat"
  status = 200